# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "163e18bcb0dcb41881cbefe2e6b02d18"
application_url = "https://relocation-wall-decided-cedar.trycloudflare.com"
embedded = true
name = "rickycito-test"
handle = "rickycito-test"

[webhooks]
api_version = "2024-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_locations,read_markets_home,read_shipping,unauthenticated_read_content,unauthenticated_read_product_pickup_locations,write_inventory,write_products,write_shipping"
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://relocation-wall-decided-cedar.trycloudflare.com/auth/callback",
  "https://relocation-wall-decided-cedar.trycloudflare.com/auth/shopify/callback",
  "https://relocation-wall-decided-cedar.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://relocation-wall-decided-cedar.trycloudflare.com"
subpath = "cn-byf-ext-config"
prefix = "apps"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
